//Ref: https://github.com/chladog/iso-639-1-dir

export const Languages = {
    aa : { name: 'Afar', nativeName: 'Afaraf', dir: 'ltr' },
    ab : { name: 'Abkhaz', nativeName: 'аҧсуа бызшәа', dir: 'ltr' },
    ae : { name: 'Avestan', nativeName: 'avesta', dir: 'ltr' },
    af : { name: 'Afrikaans', nativeName: 'Afrikaans', dir: 'ltr' },
    ak : { name: 'Akan', nativeName: 'Akan', dir: 'ltr' },
    am : { name: 'Amharic', nativeName: 'አማርኛ', dir: 'ltr' },
    an : { name: 'Aragonese', nativeName: 'aragonés', dir: 'ltr' },
    ar : { name: 'Arabic', nativeName: 'اَلْعَرَبِيَّةُ', dir: 'rtl' },
    as : { name: 'Assamese', nativeName: 'অসমীয়া', dir: 'ltr' },
    av : { name: 'Avaric', nativeName: 'авар мацӀ', dir: 'ltr' },
    ay : { name: 'Aymara', nativeName: 'aymar aru', dir: 'ltr' },
    az : { name: 'Azerbaijani', nativeName: 'azərbaycan dili', dir: 'ltr' },
    ba : { name: 'Bashkir', nativeName: 'башҡорт теле', dir: 'ltr' },
    be : { name: 'Belarusian', nativeName: 'беларуская мова', dir: 'ltr' },
    bg : { name: 'Bulgarian', nativeName: 'български език', dir: 'ltr' },
    bi : { name: 'Bislama', nativeName: 'Bislama', dir: 'ltr' },
    bm : { name: 'Bambara', nativeName: 'bamanankan', dir: 'ltr' },
    bn : { name: 'Bengali', nativeName: 'বাংলা', dir: 'ltr' },
    bo : { name: 'Tibetan', nativeName: 'བོད་ཡིག', dir: 'ltr' },
    br : { name: 'Breton', nativeName: 'brezhoneg', dir: 'ltr' },
    bs : { name: 'Bosnian', nativeName: 'bosanski jezik', dir: 'ltr' },
    ca : { name: 'Catalan', nativeName: 'Català', dir: 'ltr' },
    ce : { name: 'Chechen', nativeName: 'нохчийн мотт', dir: 'ltr' },
    ch : { name: 'Chamorro', nativeName: 'Chamoru', dir: 'ltr' },
    co : { name: 'Corsican', nativeName: 'corsu', dir: 'ltr' },
    cr : { name: 'Cree', nativeName: 'ᓀᐦᐃᔭᐍᐏᐣ', dir: 'ltr' },
    cs : { name: 'Czech', nativeName: 'čeština', dir: 'ltr' },
    cu : {
        name       : 'Old Church Slavonic',
        nativeName : 'ѩзыкъ словѣньскъ',
        dir        : 'ltr',
    },
    cv : { name: 'Chuvash', nativeName: 'чӑваш чӗлхи', dir: 'ltr' },
    cy : { name: 'Welsh', nativeName: 'Cymraeg', dir: 'ltr' },
    da : { name: 'Danish', nativeName: 'dansk', dir: 'ltr' },
    de : { name: 'German', nativeName: 'Deutsch', dir: 'ltr' },
    dv : { name: 'Divehi', nativeName: 'ދިވެހި', dir: 'rtl' },
    dz : { name: 'Dzongkha', nativeName: 'རྫོང་ཁ', dir: 'ltr' },
    ee : { name: 'Ewe', nativeName: 'Eʋegbe', dir: 'ltr' },
    el : { name: 'Greek', nativeName: 'Ελληνικά', dir: 'ltr' },
    en : { name: 'English', nativeName: 'English', dir: 'ltr' },
    eo : { name: 'Esperanto', nativeName: 'Esperanto', dir: 'ltr' },
    es : { name: 'Spanish', nativeName: 'Español', dir: 'ltr' },
    et : { name: 'Estonian', nativeName: 'eesti', dir: 'ltr' },
    eu : { name: 'Basque', nativeName: 'euskara', dir: 'ltr' },
    fa : { name: 'Persian', nativeName: 'فارسی', dir: 'rtl' },
    ff : { name: 'Fula', nativeName: 'Fulfulde', dir: 'ltr' },
    fi : { name: 'Finnish', nativeName: 'suomi', dir: 'ltr' },
    fj : { name: 'Fijian', nativeName: 'vosa Vakaviti', dir: 'ltr' },
    fo : { name: 'Faroese', nativeName: 'føroyskt', dir: 'ltr' },
    fr : { name: 'French', nativeName: 'Français', dir: 'ltr' },
    fy : { name: 'Western Frisian', nativeName: 'Frysk', dir: 'ltr' },
    ga : { name: 'Irish', nativeName: 'Gaeilge', dir: 'ltr' },
    gd : { name: 'Scottish Gaelic', nativeName: 'Gàidhlig', dir: 'ltr' },
    gl : { name: 'Galician', nativeName: 'galego', dir: 'ltr' },
    gn : { name: 'Guaraní', nativeName: "Avañe'ẽ", dir: 'ltr' },
    gu : { name: 'Gujarati', nativeName: 'ગુજરાતી', dir: 'ltr' },
    gv : { name: 'Manx', nativeName: 'Gaelg', dir: 'ltr' },
    ha : { name: 'Hausa', nativeName: 'هَوُسَ', dir: 'ltr' },
    he : { name: 'Hebrew', nativeName: 'עברית', dir: 'rtl' },
    hi : { name: 'Hindi', nativeName: 'हिन्दी', dir: 'ltr' },
    ho : { name: 'Hiri Motu', nativeName: 'Hiri Motu', dir: 'ltr' },
    hr : { name: 'Croatian', nativeName: 'Hrvatski', dir: 'ltr' },
    ht : { name: 'Haitian', nativeName: 'Kreyòl ayisyen', dir: 'ltr' },
    hu : { name: 'Hungarian', nativeName: 'magyar', dir: 'ltr' },
    hy : { name: 'Armenian', nativeName: 'Հայերեն', dir: 'ltr' },
    hz : { name: 'Herero', nativeName: 'Otjiherero', dir: 'ltr' },
    ia : { name: 'Interlingua', nativeName: 'Interlingua', dir: 'ltr' },
    id : { name: 'Indonesian', nativeName: 'Bahasa Indonesia', dir: 'ltr' },
    ie : { name: 'Interlingue', nativeName: 'Interlingue', dir: 'ltr' },
    ig : { name: 'Igbo', nativeName: 'Asụsụ Igbo', dir: 'ltr' },
    ii : { name: 'Nuosu', nativeName: 'ꆈꌠ꒿ Nuosuhxop', dir: 'ltr' },
    ik : { name: 'Inupiaq', nativeName: 'Iñupiaq', dir: 'ltr' },
    io : { name: 'Ido', nativeName: 'Ido', dir: 'ltr' },
    is : { name: 'Icelandic', nativeName: 'Íslenska', dir: 'ltr' },
    it : { name: 'Italian', nativeName: 'Italiano', dir: 'ltr' },
    iu : { name: 'Inuktitut', nativeName: 'ᐃᓄᒃᑎᑐᑦ', dir: 'ltr' },
    ja : { name: 'Japanese', nativeName: '日本語', dir: 'ttb' },
    jv : { name: 'Javanese', nativeName: 'basa Jawa', dir: 'ltr' },
    ka : { name: 'Georgian', nativeName: 'ქართული', dir: 'ltr' },
    kg : { name: 'Kongo', nativeName: 'Kikongo', dir: 'ltr' },
    ki : { name: 'Kikuyu', nativeName: 'Gĩkũyũ', dir: 'ltr' },
    kj : { name: 'Kwanyama', nativeName: 'Kuanyama', dir: 'ltr' },
    kk : { name: 'Kazakh', nativeName: 'қазақ тілі', dir: 'ltr' },
    kl : { name: 'Kalaallisut', nativeName: 'kalaallisut', dir: 'ltr' },
    km : { name: 'Khmer', nativeName: 'ខេមរភាសា', dir: 'ltr' },
    kn : { name: 'Kannada', nativeName: 'ಕನ್ನಡ', dir: 'ltr' },
    ko : { name: 'Korean', nativeName: '한국어', dir: 'ttb' },
    kr : { name: 'Kanuri', nativeName: 'Kanuri', dir: 'ltr' },
    ks : { name: 'Kashmiri', nativeName: 'कश्मीरी', dir: 'rtl' },
    ku : { name: 'Kurdish', nativeName: 'Kurdî', dir: 'rtl' },
    kv : { name: 'Komi', nativeName: 'коми кыв', dir: 'ltr' },
    kw : { name: 'Cornish', nativeName: 'Kernewek', dir: 'ltr' },
    ky : { name: 'Kyrgyz', nativeName: 'Кыргызча', dir: 'ltr' },
    la : { name: 'Latin', nativeName: 'latine', dir: 'ltr' },
    lb : { name: 'Luxembourgish', nativeName: 'Lëtzebuergesch', dir: 'ltr' },
    lg : { name: 'Ganda', nativeName: 'Luganda', dir: 'ltr' },
    li : { name: 'Limburgish', nativeName: 'Limburgs', dir: 'ltr' },
    ln : { name: 'Lingala', nativeName: 'Lingála', dir: 'ltr' },
    lo : { name: 'Lao', nativeName: 'ພາສາລາວ', dir: 'ltr' },
    lt : { name: 'Lithuanian', nativeName: 'lietuvių kalba', dir: 'ltr' },
    lu : { name: 'Luba-Katanga', nativeName: 'Kiluba', dir: 'ltr' },
    lv : { name: 'Latvian', nativeName: 'latviešu valoda', dir: 'ltr' },
    mg : { name: 'Malagasy', nativeName: 'fiteny malagasy', dir: 'ltr' },
    mh : { name: 'Marshallese', nativeName: 'Kajin M̧ajeļ', dir: 'ltr' },
    mi : { name: 'Māori', nativeName: 'te reo Māori', dir: 'ltr' },
    mk : { name: 'Macedonian', nativeName: 'македонски јазик', dir: 'ltr' },
    ml : { name: 'Malayalam', nativeName: 'മലയാളം', dir: 'ltr' },
    mn : { name: 'Mongolian', nativeName: 'Монгол хэл', dir: 'ttb' },
    mr : { name: 'Marathi', nativeName: 'मराठी', dir: 'ltr' },
    ms : { name: 'Malay', nativeName: 'Bahasa Melayu', dir: 'ltr' },
    mt : { name: 'Maltese', nativeName: 'Malti', dir: 'ltr' },
    my : { name: 'Burmese', nativeName: 'ဗမာစာ', dir: 'ltr' },
    na : { name: 'Nauru', nativeName: 'Dorerin Naoero', dir: 'ltr' },
    nb : { name: 'Norwegian Bokmål', nativeName: 'Norsk bokmål', dir: 'ltr' },
    nd : { name: 'Northern Ndebele', nativeName: 'isiNdebele', dir: 'ltr' },
    ne : { name: 'Nepali', nativeName: 'नेपाली', dir: 'ltr' },
    ng : { name: 'Ndonga', nativeName: 'Owambo', dir: 'ltr' },
    nl : { name: 'Dutch', nativeName: 'Nederlands', dir: 'ltr' },
    nn : {
        name       : 'Norwegian Nynorsk',
        nativeName : 'Norsk nynorsk',
        dir        : 'ltr',
    },
    no : { name: 'Norwegian', nativeName: 'Norsk', dir: 'ltr' },
    nr : { name: 'Southern Ndebele', nativeName: 'isiNdebele', dir: 'ltr' },
    nv : { name: 'Navajo', nativeName: 'Diné bizaad', dir: 'ltr' },
    ny : { name: 'Chichewa', nativeName: 'chiCheŵa', dir: 'ltr' },
    oc : { name: 'Occitan', nativeName: 'occitan', dir: 'ltr' },
    oj : { name: 'Ojibwe', nativeName: 'ᐊᓂᔑᓈᐯᒧᐎᓐ', dir: 'ltr' },
    om : { name: 'Oromo', nativeName: 'Afaan Oromoo', dir: 'ltr' },
    or : { name: 'Oriya', nativeName: 'ଓଡ଼ିଆ', dir: 'ltr' },
    os : { name: 'Ossetian', nativeName: 'ирон æвзаг', dir: 'ltr' },
    pa : { name: 'Panjabi', nativeName: 'ਪੰਜਾਬੀ', dir: 'rtl' },
    pi : { name: 'Pāli', nativeName: 'पाऴि', dir: 'ltr' },
    pl : { name: 'Polish', nativeName: 'Polski', dir: 'ltr' },
    ps : { name: 'Pashto', nativeName: 'پښتو', dir: 'rtl' },
    pt : { name: 'Portuguese', nativeName: 'Português', dir: 'ltr' },
    qu : { name: 'Quechua', nativeName: 'Runa Simi', dir: 'ltr' },
    rm : { name: 'Romansh', nativeName: 'rumantsch grischun', dir: 'ltr' },
    rn : { name: 'Kirundi', nativeName: 'Ikirundi', dir: 'ltr' },
    ro : { name: 'Romanian', nativeName: 'Română', dir: 'ltr' },
    ru : { name: 'Russian', nativeName: 'Русский', dir: 'ltr' },
    rw : { name: 'Kinyarwanda', nativeName: 'Ikinyarwanda', dir: 'ltr' },
    sa : { name: 'Sanskrit', nativeName: 'संस्कृतम्', dir: 'ltr' },
    sc : { name: 'Sardinian', nativeName: 'sardu', dir: 'ltr' },
    sd : { name: 'Sindhi', nativeName: 'सिन्धी', dir: 'rtl' },
    se : { name: 'Northern Sami', nativeName: 'Davvisámegiella', dir: 'ltr' },
    sg : { name: 'Sango', nativeName: 'yângâ tî sängö', dir: 'ltr' },
    si : { name: 'Sinhala', nativeName: 'සිංහල', dir: 'ltr' },
    sk : { name: 'Slovak', nativeName: 'slovenčina', dir: 'ltr' },
    sl : { name: 'Slovenian', nativeName: 'slovenščina', dir: 'ltr' },
    sm : { name: 'Samoan', nativeName: "gagana fa'a Samoa", dir: 'ltr' },
    sn : { name: 'Shona', nativeName: 'chiShona', dir: 'ltr' },
    so : { name: 'Somali', nativeName: 'Soomaaliga', dir: 'ltr' },
    sq : { name: 'Albanian', nativeName: 'Shqip', dir: 'ltr' },
    sr : { name: 'Serbian', nativeName: 'српски језик', dir: 'ltr' },
    ss : { name: 'Swati', nativeName: 'SiSwati', dir: 'ltr' },
    st : { name: 'Southern Sotho', nativeName: 'Sesotho', dir: 'ltr' },
    su : { name: 'Sundanese', nativeName: 'Basa Sunda', dir: 'ltr' },
    sv : { name: 'Swedish', nativeName: 'Svenska', dir: 'ltr' },
    sw : { name: 'Swahili', nativeName: 'Kiswahili', dir: 'ltr' },
    ta : { name: 'Tamil', nativeName: 'தமிழ்', dir: 'ltr' },
    te : { name: 'Telugu', nativeName: 'తెలుగు', dir: 'ltr' },
    tg : { name: 'Tajik', nativeName: 'тоҷикӣ', dir: 'ltr' },
    th : { name: 'Thai', nativeName: 'ไทย', dir: 'ltr' },
    ti : { name: 'Tigrinya', nativeName: 'ትግርኛ', dir: 'ltr' },
    tk : { name: 'Turkmen', nativeName: 'Türkmençe', dir: 'rtl' },
    tl : { name: 'Tagalog', nativeName: 'Wikang Tagalog', dir: 'ltr' },
    tn : { name: 'Tswana', nativeName: 'Setswana', dir: 'ltr' },
    to : { name: 'Tonga', nativeName: 'faka Tonga', dir: 'ltr' },
    tr : { name: 'Turkish', nativeName: 'Türkçe', dir: 'ltr' },
    ts : { name: 'Tsonga', nativeName: 'Xitsonga', dir: 'ltr' },
    tt : { name: 'Tatar', nativeName: 'татар теле', dir: 'ltr' },
    tw : { name: 'Twi', nativeName: 'Twi', dir: 'ltr' },
    ty : { name: 'Tahitian', nativeName: 'Reo Tahiti', dir: 'ltr' },
    ug : { name: 'Uyghur', nativeName: 'ئۇيغۇرچە‎', dir: 'rtl' },
    uk : { name: 'Ukrainian', nativeName: 'Українська', dir: 'ltr' },
    ur : { name: 'Urdu', nativeName: 'اردو', dir: 'rtl' },
    uz : { name: 'Uzbek', nativeName: 'Ўзбек', dir: 'ltr' },
    ve : { name: 'Venda', nativeName: 'Tshivenḓa', dir: 'ltr' },
    vi : { name: 'Vietnamese', nativeName: 'Tiếng Việt', dir: 'ttb' },
    vo : { name: 'Volapük', nativeName: 'Volapük', dir: 'ltr' },
    wa : { name: 'Walloon', nativeName: 'walon', dir: 'ltr' },
    wo : { name: 'Wolof', nativeName: 'Wollof', dir: 'ltr' },
    xh : { name: 'Xhosa', nativeName: 'isiXhosa', dir: 'ltr' },
    yi : { name: 'Yiddish', nativeName: 'ייִדיש', dir: 'rtl' },
    yo : { name: 'Yoruba', nativeName: 'Yorùbá', dir: 'ltr' },
    za : { name: 'Zhuang', nativeName: 'Saɯ cueŋƅ', dir: 'ttb' },
    zh : { name: 'Chinese', nativeName: '中文', dir: 'ttb' },
    zu : { name: 'Zulu', nativeName: 'isiZulu', dir: 'ltr' },
} as const;

type AllValuesOf<T> = T extends any ? T[keyof T] : never;

export type LanguageCode = keyof typeof Languages;
export type LanguageName = AllValuesOf<typeof Languages>["name"];
export type LanguageNativeName = AllValuesOf<typeof Languages>["nativeName"];
export type LanguageDir = AllValuesOf<typeof Languages>["dir"];

export interface Language {
    Name      : LanguageName,
    NativeName: LanguageNativeName,
    Direction : LanguageDir,
    Code      : LanguageCode;
}

export const getLanguage = (code): Language | null => {
    if (!code) {
        return null;
    }
    const langCode = code.toLowerCase();
    const exists = Object.hasOwn(Languages, langCode);
    if (!exists) {
        return null;
    }
    const lang = Languages[langCode];
    const language: Language = {
        Name       : lang.name,
        NativeName : lang.nativeName,
        Direction  : lang.dir,
        Code       : lang.Code,
    };
    return language;
};
